const std = @import("std");
pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});
    const mod = b.addModule("zander", .{ .root_source_file = b.path("src/root.zig"), .target = target, .optimize = optimize });
    const backend = b.addOptions();
    backend.addOption(bool, "simd", b.option(bool, "simd", "Use portable vector NNUE kernels instead of the scalar reference") orelse false);
    backend.addOption(bool, "prefetch", b.option(bool, "prefetch", "Issue the reference TT/history prefetch hints") orelse true);
    mod.addOptions("backend", backend);
    const exe_mod = b.createModule(.{ .root_source_file = b.path("src/main.zig"), .target = target, .optimize = optimize });
    exe_mod.addImport("zander", mod);
    const exe = b.addExecutable(.{ .name = "zander", .root_module = exe_mod });
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    if (b.args) |args| run.addArgs(args);
    b.step("run", "Run the UCI engine or diagnostic CLI").dependOn(&run.step);
    const unit = b.addTest(.{ .root_module = mod });
    const test_step = b.step("test", "Run Zig unit tests");
    test_step.dependOn(&b.addRunArtifact(unit).step);
    const python_check = b.addSystemCommand(&.{ "uvx", "ty==0.0.32", "check" });
    python_check.setCwd(b.path("."));
    b.step("python-check", "Type-check Python scripts and tests with ty").dependOn(&python_check.step);
    // The C++ oracle is host-only; keep it outside the portable library.
    const cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-c" });
    cpp.addFileArg(b.path("tests/oracle.cpp"));
    cpp.addArg("-o");
    const obj = cpp.addOutputFileArg("oracle.o");
    const diff_mod = b.createModule(.{ .root_source_file = b.path("tests/differential.zig"), .target = b.graph.host, .optimize = optimize });
    diff_mod.addImport("zander", b.createModule(.{ .root_source_file = b.path("src/root.zig"), .target = b.graph.host, .optimize = optimize }));
    diff_mod.import_table.get("zander").?.addOptions("backend", backend);
    diff_mod.addObjectFile(obj);
    const reference_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-ffunction-sections", "-fdata-sections" });
    reference_cpp.addFileArg(b.path("tests/position_reference.cpp"));
    reference_cpp.addFileArg(b.path("vendor/stockfish/src/uci.cpp"));
    reference_cpp.addFileArg(b.path("vendor/stockfish/src/tt.cpp"));
    const tt_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-ffunction-sections", "-fdata-sections" });
    tt_cpp.addFileArg(b.path("tests/tt_reference.cpp"));
    const nnue_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT" });
    nnue_cpp.addFileArg(b.path("tests/nnue_reference.cpp"));
    const tablebase_path = b.option([]const u8, "tablebases", "Path to the small Syzygy regression tables");
    const network_path = b.option([]const u8, "network", "Path to the pinned NNUE weights for integration tests");
    const network_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-DNNUE_EMBEDDING_OFF", "-ffunction-sections", "-fdata-sections" });
    network_cpp.addFileArg(b.path("tests/network_reference.cpp"));
    network_cpp.addFileArg(b.path("vendor/stockfish/src/uci.cpp"));
    network_cpp.addFileArg(b.path("vendor/stockfish/src/tt.cpp"));
    const history_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT" });
    history_cpp.addFileArg(b.path("tests/history_reference.cpp"));
    const movepick_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-ffunction-sections", "-fdata-sections" });
    movepick_cpp.addFileArg(b.path("tests/movepick_reference.cpp"));
    movepick_cpp.addFileArg(b.path("vendor/stockfish/src/uci.cpp"));
    movepick_cpp.addFileArg(b.path("vendor/stockfish/src/tt.cpp"));
    movepick_cpp.addFileArg(b.path("vendor/stockfish/src/memory.cpp"));
    const search_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-ffunction-sections", "-fdata-sections" });
    search_cpp.addFileArg(b.path("tests/search_reference.cpp"));
    const worker_cpp = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-DNNUE_EMBEDDING_OFF", "-ffunction-sections", "-fdata-sections", "-pthread" });
    worker_cpp.addFileArg(b.path("tests/search_worker_reference.cpp"));
    for ([_][]const u8{ "uci", "memory", "misc", "thread", "ucioption", "movepick", "timeman", "syzygy/tbprobe", "score" }) |source| worker_cpp.addFileArg(b.path(b.fmt("vendor/stockfish/src/{s}.cpp", .{source})));
    // Track the pinned source directory, including transitive header includes.
    var upstream = std.Io.Dir.cwd().openDir(b.graph.io, b.pathFromRoot("vendor/stockfish/src"), .{ .iterate = true }) catch @panic("Initialize the Stockfish submodule first");
    defer upstream.close(b.graph.io);
    var upstream_inputs: std.ArrayList(std.Build.LazyPath) = .empty;
    var walker = upstream.walk(b.allocator) catch @panic("Cannot walk Stockfish sources");
    defer walker.deinit();
    while (walker.next(b.graph.io) catch @panic("Cannot read Stockfish sources")) |entry| {
        if (entry.kind == .file) {
            const input = b.path(b.fmt("vendor/stockfish/src/{s}", .{entry.path}));
            upstream_inputs.append(b.allocator, input) catch @panic("Out of memory");
            reference_cpp.addFileInput(input);
            tt_cpp.addFileInput(input);
            nnue_cpp.addFileInput(input);
            cpp.addFileInput(input);
            network_cpp.addFileInput(input);
            history_cpp.addFileInput(input);
            movepick_cpp.addFileInput(input);
            search_cpp.addFileInput(input);
            worker_cpp.addFileInput(input);
        }
    }
    reference_cpp.addArg("-Wl,--gc-sections");
    reference_cpp.addArg("-o");
    const reference_exe = reference_cpp.addOutputFileArg("position-reference");
    const reference_run = std.Build.Step.Run.create(b, "generate position reference");
    reference_run.addFileArg(reference_exe);
    reference_run.addFileArg(b.path("tests/positions.txt"));
    const fixture = reference_run.captureStdOut(.{ .basename = "position_reference.zig" });
    diff_mod.addAnonymousImport("position_reference", .{ .root_source_file = fixture });
    tt_cpp.addArg("-Wl,--gc-sections");
    tt_cpp.addArg("-o");
    const tt_exe = tt_cpp.addOutputFileArg("tt-reference");
    const tt_run = std.Build.Step.Run.create(b, "generate TT reference");
    tt_run.addFileArg(tt_exe);
    diff_mod.addAnonymousImport("tt_reference", .{ .root_source_file = tt_run.captureStdOut(.{ .basename = "tt_reference.zig" }) });
    nnue_cpp.addArg("-o");
    const nnue_exe = nnue_cpp.addOutputFileArg("nnue-reference");
    const nnue_run = std.Build.Step.Run.create(b, "generate NNUE reference");
    nnue_run.addFileArg(nnue_exe);
    diff_mod.addAnonymousImport("nnue_reference", .{ .root_source_file = nnue_run.captureStdOut(.{ .basename = "nnue_reference.zig" }) });
    if (network_path) |path| {
        network_cpp.addArgs(&.{ "-Wl,--gc-sections", "-o" });
        const network_exe = network_cpp.addOutputFileArg("network-reference");
        const network_run = std.Build.Step.Run.create(b, "generate real NNUE reference");
        network_run.addFileArg(network_exe);
        network_run.addFileArg(.{ .cwd_relative = path });
        network_run.addFileArg(b.path("tests/positions.txt"));
        const network_mod = b.createModule(.{ .root_source_file = b.path("tests/network.zig"), .target = b.graph.host, .optimize = optimize });
        network_mod.addImport("zander", diff_mod.import_table.get("zander").?);
        network_mod.addAnonymousImport("reference", .{ .root_source_file = network_run.captureStdOut(.{ .basename = "network_reference.zig" }) });
        const options = b.addOptions();
        options.addOption([]const u8, "network_path", b.pathFromRoot(path));
        options.addOption(?[]const u8, "tablebase_path", tablebase_path);
        network_mod.addOptions("options", options);
        const network_test = b.addTest(.{ .root_module = network_mod });
        b.step("network-test", "Compare real NNUE weights and incremental evaluation with Stockfish").dependOn(&b.addRunArtifact(network_test).step);
        worker_cpp.addArgs(&.{ "-Wl,--gc-sections", "-o" });
        const engine_mod = b.createModule(.{ .root_source_file = b.path("tests/engine.zig"), .target = b.graph.host, .optimize = optimize });
        engine_mod.addImport("zander", diff_mod.import_table.get("zander").?);
        engine_mod.addOptions("options", options);
        const uci_run = b.addSystemCommand(&.{"python3"});
        uci_run.addFileArg(b.path("tests/uci.py"));
        uci_run.addArtifactArg(exe);
        uci_run.addFileArg(.{ .cwd_relative = path });
        if (tablebase_path) |tb_path| uci_run.addArgs(&.{ "--tablebases", tb_path });
        b.step("uci-test", "Exercise UCI through real pipes").dependOn(&uci_run.step);
        const engine_test = b.addTest(.{ .root_module = engine_mod });
        b.step("engine-test", "Check persistent engine state and resource replacement").dependOn(&b.addRunArtifact(engine_test).step);
        const worker_exe = worker_cpp.addOutputFileArg("search-worker-reference");
        const worker_run = std.Build.Step.Run.create(b, "generate search worker reference");
        worker_run.addFileArg(worker_exe);
        worker_run.addFileArg(.{ .cwd_relative = path });
        worker_run.addFileArg(b.path("tests/positions.txt"));
        const worker_mod = b.createModule(.{ .root_source_file = b.path("tests/search_worker.zig"), .target = b.graph.host, .optimize = optimize });
        worker_mod.addImport("zander", diff_mod.import_table.get("zander").?);
        worker_mod.addOptions("options", options);
        worker_mod.addAnonymousImport("reference", .{ .root_source_file = worker_run.captureStdOut(.{ .basename = "search_worker_reference.zig" }) });
        const worker_test = b.addTest(.{ .root_module = worker_mod });
        const worker_test_run = b.addRunArtifact(worker_test);
        b.step("search-test", "Compare single-worker search and histories with Stockfish").dependOn(&worker_test_run.step);
        b.step("quiescence-test", "Alias for search-test").dependOn(&worker_test_run.step);
    }
    if (tablebase_path) |path| {
        const positions = b.addSystemCommand(&.{"python3"});
        positions.addFileArg(b.path("tests/syzygy_positions.py"));
        positions.addFileInput(b.path("tests/syzygy_manifest.json"));
        const cpp_tb = b.addSystemCommand(&.{ "c++", "-std=c++17", "-O2", "-DNDEBUG", "-DIS_64BIT", "-ffunction-sections", "-fdata-sections", "-pthread" });
        for (upstream_inputs.items) |input| cpp_tb.addFileInput(input);
        cpp_tb.addFileArg(b.path("tests/syzygy_reference.cpp"));
        cpp_tb.addFileArg(b.path("vendor/stockfish/src/syzygy/tbprobe.cpp"));
        cpp_tb.addFileArg(b.path("vendor/stockfish/src/uci.cpp"));
        cpp_tb.addFileArg(b.path("vendor/stockfish/src/tt.cpp"));
        cpp_tb.addFileArg(b.path("vendor/stockfish/src/misc.cpp"));
        cpp_tb.addArgs(&.{ "-Wl,--gc-sections", "-o" });
        const oracle = cpp_tb.addOutputFileArg("syzygy-reference");
        const reference = std.Build.Step.Run.create(b, "generate Syzygy reference");
        reference.addFileArg(oracle);
        reference.addArg(path);
        var tablebase_dir = std.Io.Dir.cwd().openDir(b.graph.io, path, .{ .iterate = true }) catch @panic("Fetch the Syzygy regression tables first");
        defer tablebase_dir.close(b.graph.io);
        var tablebase_files = tablebase_dir.iterate();
        while (tablebase_files.next(b.graph.io) catch @panic("Cannot enumerate Syzygy regression files")) |file| {
            if (file.kind == .file) reference.addFileInput(.{ .cwd_relative = std.fs.path.join(b.allocator, &.{ path, file.name }) catch @panic("Out of memory") });
        }
        reference.addFileArg(positions.captureStdOut(.{ .basename = "syzygy-positions.txt" }));
        const tb_options = b.addOptions();
        tb_options.addOption([]const u8, "tablebase_path", path);
        const tb_mod = b.createModule(.{ .root_source_file = b.path("tests/syzygy.zig"), .target = b.graph.host, .optimize = optimize });
        tb_mod.addImport("zander", diff_mod.import_table.get("zander").?);
        tb_mod.addOptions("options", tb_options);
        tb_mod.addAnonymousImport("reference", .{ .root_source_file = reference.captureStdOut(.{ .basename = "syzygy_reference.zig" }) });
        const tb_test = b.addTest(.{ .root_module = tb_mod });
        b.step("syzygy-test", "Compare native WDL and DTZ probing with Stockfish").dependOn(&b.addRunArtifact(tb_test).step);
    }
    history_cpp.addArg("-o");
    const history_exe = history_cpp.addOutputFileArg("history-reference");
    const history_run = std.Build.Step.Run.create(b, "generate history reference");
    history_run.addFileArg(history_exe);
    diff_mod.addAnonymousImport("history_reference", .{ .root_source_file = history_run.captureStdOut(.{ .basename = "history_reference.zig" }) });
    movepick_cpp.addArgs(&.{ "-Wl,--gc-sections", "-o" });
    const movepick_exe = movepick_cpp.addOutputFileArg("movepick-reference");
    const movepick_run = std.Build.Step.Run.create(b, "generate move ordering reference");
    movepick_run.addFileArg(movepick_exe);
    movepick_run.addFileArg(b.path("tests/positions.txt"));
    diff_mod.addAnonymousImport("movepick_reference", .{ .root_source_file = movepick_run.captureStdOut(.{ .basename = "movepick_reference.zig" }) });
    search_cpp.addArgs(&.{ "-Wl,--gc-sections", "-o" });
    const search_exe = search_cpp.addOutputFileArg("search-reference");
    const search_run = std.Build.Step.Run.create(b, "generate search helper reference");
    search_run.addFileArg(search_exe);
    diff_mod.addAnonymousImport("search_reference", .{ .root_source_file = search_run.captureStdOut(.{ .basename = "search_reference.zig" }) });
    const diff = b.addTest(.{ .root_module = diff_mod });
    const diff_step = b.step("differential", "Compare with pinned Stockfish C++ (requires host c++)");
    diff_step.dependOn(&b.addRunArtifact(diff).step);
}
