const std = @import("std");
const z = @import("zander");
test "quiescence scores, nodes, PV and TT writes match pinned Stockfish" {
    const allocator = std.testing.allocator;
    const bytes = try std.Io.Dir.cwd().readFileAlloc(std.testing.io, @import("options").network_path, allocator, .limited(200 * 1024 * 1024));
    defer allocator.free(bytes);
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
    try std.testing.expectEqualStrings(z.nnue_network.default_sha256, &std.fmt.bytesToHex(digest, .lower));
    const network = try allocator.create(z.nnue_network.Network);
    defer allocator.destroy(network);
    _ = try network.load(bytes);
    const accumulators = try allocator.create(z.nnue_accumulator.Stack);
    defer allocator.destroy(accumulators);
    const caches = try allocator.create(z.nnue_accumulator.Caches);
    defer allocator.destroy(caches);
    caches.clear(&network.transformer);
    const tables = try allocator.create(z.attacks.Tables);
    defer allocator.destroy(tables);
    tables.init();
    const keys = try allocator.create(z.position_keys.PositionKeys);
    defer allocator.destroy(keys);
    keys.init();
    const main = try allocator.create(z.history.ButterflyHistory);
    defer allocator.destroy(main);
    z.history.fill(main, -5);
    const low = try allocator.create(z.history.LowPlyHistory);
    defer allocator.destroy(low);
    z.history.fill(low, 102);
    const capture = try allocator.create(z.history.CapturePieceToHistory);
    defer allocator.destroy(capture);
    z.history.fill(capture, -742);
    const correction = try allocator.alloc(z.history.CorrectionEntry, z.history.correction_history_base_size);
    defer allocator.free(correction);
    const pawn = try allocator.alloc(z.history.PawnEntry, z.history.pawn_history_base_size);
    defer allocator.free(pawn);
    const continuation = try allocator.create(z.history.ContinuationHistoryBlock);
    defer allocator.destroy(continuation);
    const continuation_correction = try allocator.create(z.history.ContinuationCorrectionHistory);
    defer allocator.destroy(continuation_correction);
    z.history.fill(continuation_correction, 5);
    var shared = try z.history.SharedHistories.init(1, correction, continuation, pawn);
    shared.clearRange(0, 1);
    const clusters = try allocator.alignedAlloc(z.tt.Cluster, .@"64", 32768);
    defer allocator.free(clusters);
    var table = z.tt.Table.init(clusters);
    const worker = try allocator.create(z.quiescence.Worker);
    defer allocator.destroy(worker);
    worker.* = .{ .network = network, .accumulators = accumulators, .caches = caches, .table = &table, .main_history = main, .low_ply_history = low, .capture_history = capture, .shared = &shared, .continuation_correction = continuation_correction };
    var lines: [100][]const u8 = undefined;
    var iter = std.mem.tokenizeScalar(u8, @embedFile("positions.txt"), '\n');
    var count: usize = 0;
    while (iter.next()) |line| : (count += 1) lines[count] = line;
    for (@import("reference").cases, 0..) |case, case_index| {
        errdefer std.debug.print("Quiescence case {d}, root {d}, warm {any}\n", .{ case_index, case.root, case.warm });
        var pos: z.position.Position = undefined;
        var states: [9]z.position.StateInfo = undefined;
        try pos.set(lines[case.root][2..], lines[case.root][0] == '1', &states[0], tables, keys);
        for (case.path, 1..) |move, i| pos.doMove(.{ .data = move }, &states[i]);
        const original_key = pos.key();
        if (!case.warm) {
            table.clear();
            table.newSearch();
        }
        var pv: z.search_support.PV = .{};
        const score = if (case.pv_node) worker.run(true, &pos, &pv, case.alpha, case.beta) else worker.run(false, &pos, &pv, case.alpha, case.beta);
        try std.testing.expectEqual(case.score, score);
        try std.testing.expectEqual(case.nodes, worker.nodes);
        try std.testing.expectEqual(case.sel_depth, worker.sel_depth);
        try std.testing.expectEqual(case.pv.len, pv.len);
        for (case.pv, pv.slice()) |expected, actual| try std.testing.expectEqual(expected, actual.data);
        var checksum: u64 = 14695981039346656037;
        for (std.mem.sliceAsBytes(clusters)) |byte| checksum = (checksum ^ byte) *% 1099511628211;
        try std.testing.expectEqual(case.tt_checksum, checksum);
        try std.testing.expectEqual(original_key, pos.key());
        try std.testing.expect(pos.st == &states[case.path.len]);
        try std.testing.expectEqual(@as(usize, 1), accumulators.size);
    }
}
